# -*- coding: utf-8 -*-
"""234311021_Nabila Carrissa Dewi_UTS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ABYcrZD26KDaQkccXvv1QQrfkw5IvOmO

# **Instal Kaggle API**
"""

!pip install kaggle

"""# **Unduh Dataset dari Kaggle**"""

import os

# buat folder dataset
os.makedirs("dataset", exist_ok=True)

# download dataset dari kaggle
os.system("kaggle datasets download -d karansolanki01/garbage-classification -p dataset")

# extract zip
import zipfile

zip_path = "dataset/garbage-classification.zip"
with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall("dataset")

print("Dataset berhasil didownload dan diextract!")

"""# **1. Import Library**"""

!pip install tensorflow scikit-learn opencv-python pillow

!pip install scikit-image matplotlib seaborn pandas joblib

import os
import re
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
import cv2
import pickle
import json
from pathlib import Path
from datetime import datetime
from collections import Counter

# Scikit-learn
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import (
    accuracy_score, classification_report,
    confusion_matrix, ConfusionMatrixDisplay
)
from skimage.feature import hog  # HOG feature extraction

# TensorFlow / Keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks
from tensorflow.keras.preprocessing.image import ImageDataGenerator

warnings.filterwarnings('ignore')
tf.random.set_seed(42)
np.random.seed(42)

print("=" * 60)
print("  PIPELINE KLASIFIKASI GAMBAR SAMPAH")
print(f"  Tanggal: {datetime.now().strftime('%Y-%m-%d %H:%M')}")
print("=" * 60)
print(f"TensorFlow versi: {tf.__version__}")

# ===========================================================================
# BAGIAN B: KONFIGURASI & PARAMETER GLOBAL
# ===========================================================================
CONFIG = {
    # --- Path dataset ---
    # Ubah path ini sesuai lokasi dataset Kaggle Anda setelah diekstrak
    # Dataset: https://www.kaggle.com/datasets/asdasdasasdas/garbage-classification
    "DATASET_DIR"  : "/content/dataset/Data/Garbage_Classification",   # root folder dataset

    # --- Parameter gambar ---
    "IMG_SIZE"     : (224, 224),   # ukuran resize (tinggi, lebar)
    "IMG_SIZE_HOG" : (64, 64),     # ukuran HOG untuk ML klasik (lebih ringan)
    "CHANNELS"     : 3,            # RGB

    # --- Pembagian data (Haqqi et al., 2024: 70/20/10) ---
    "TRAIN_RATIO"  : 0.70,
    "VAL_RATIO"    : 0.20,
    "TEST_RATIO"   : 0.10,

    # --- Pelatihan CNN ---
    "BATCH_SIZE"   : 32,
    "EPOCHS"       : 50,
    "LEARNING_RATE": 1e-4,
    "DROPOUT_RATE" : 0.5,

    # --- Parameter SVM (Yulita et al., 2023: kernel RBF terbaik) ---
    "SVM_KERNEL"   : "rbf",
    "SVM_C"        : 10.0,
    "SVM_GAMMA"    : "scale",

    # --- Parameter Decision Tree (Jijo & Abdulazeez, 2021) ---
    "DT_MAX_DEPTH" : None,        # None = tumbuh penuh, sesuaikan jika overfit
    "DT_CRITERION" : "gini",      # atau "entropy" (ID3)

    # --- Parameter Random Forest (Lau et al., 2025: n_estimators=150) ---
    "RF_N_ESTIMATORS" : 150,
    "RF_MAX_DEPTH"    : None,
    "RF_RANDOM_STATE" : 42,

    # --- Output ---
    "OUTPUT_DIR"   : "./output_model",
    "RANDOM_STATE" : 42,
}

# Label kelas dataset Kaggle Garbage Classification
KELAS = ["Battery", "Cardboard", "Clothes", "Glass", "Metal", "Paper", "Plastic"]
NUM_KELAS = len(KELAS)

os.makedirs(CONFIG["OUTPUT_DIR"], exist_ok=True)
print(f"\nOutput akan disimpan di: {CONFIG['OUTPUT_DIR']}/")

# ===========================================================================
# BAGIAN C: PREPROCESSING & LOAD DATASET
# ===========================================================================
# Catatan metodologi:
# Haqqi et al. (2024) menerapkan cropping, Gaussian filter, dan augmentasi
# untuk meningkatkan kualitas data.
# Lau et al. (2025) menggunakan normalisasi dan ekstraksi HOG.
# Penelitian ini menggabungkan kedua pendekatan tersebut.

def load_and_preprocess_dataset(dataset_dir, img_size, img_size_hog):
    """
    Memuat seluruh dataset gambar, melakukan preprocessing, dan
    mengembalikan array gambar beserta label-nya.

    Args:
        dataset_dir  : path root folder dataset
        img_size     : tuple (h, w) untuk CNN
        img_size_hog : tuple (h, w) untuk HOG / ML klasik

    Returns:
        images_cnn  : array (N, H, W, 3) ternormalisasi untuk CNN
        images_hog  : array (N, H, W, 3) untuk ekstraksi HOG
        labels      : array string nama kelas
        label_enc   : LabelEncoder yang sudah di-fit
    """
    images_cnn  = []
    images_hog  = []
    labels      = []
    dataset_dir = Path(dataset_dir)

    print("\n[LOAD] Memuat dataset ...")
    for kelas in KELAS:
        kelas_dir = dataset_dir / kelas
        if not kelas_dir.exists():
            print(f"  [PERINGATAN] Folder tidak ditemukan: {kelas_dir}")
            continue
        gambar_files = list(kelas_dir.glob("*.jpg")) + \
                       list(kelas_dir.glob("*.jpeg")) + \
                       list(kelas_dir.glob("*.png"))
        print(f"  Kelas '{kelas}': {len(gambar_files)} gambar")

        for filepath in gambar_files:
            img_bgr = cv2.imread(str(filepath))
            if img_bgr is None:
                continue  # lewati gambar rusak

            img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)

            # --- Gaussian filter untuk noise reduction (Haqqi et al., 2024) ---
            img_filtered = cv2.GaussianBlur(img_rgb, (3, 3), 0)

            # --- Resize untuk CNN ---
            img_cnn = cv2.resize(img_filtered, (img_size[1], img_size[0]))
            img_cnn = img_cnn.astype(np.float32) / 255.0   # normalisasi [0,1]

            # --- Resize untuk HOG (ukuran lebih kecil) ---
            img_hog = cv2.resize(img_filtered, (img_size_hog[1], img_size_hog[0]))

            images_cnn.append(img_cnn)
            images_hog.append(img_hog)
            labels.append(kelas)

    images_cnn = np.array(images_cnn, dtype=np.float32)
    images_hog = np.array(images_hog, dtype=np.uint8)
    labels     = np.array(labels)

    # Encode label ke integer
    label_enc = LabelEncoder()
    label_enc.fit(KELAS)

    print(f"\n  Total gambar dimuat : {len(labels)}")
    print(f"  Distribusi kelas    : {dict(Counter(labels))}")
    return images_cnn, images_hog, labels, label_enc


# ===========================================================================
# BAGIAN D: EKSTRAKSI FITUR
# ===========================================================================
# CNN : fitur diekstraksi secara otomatis oleh lapisan konvolusi
# ML  : fitur diekstraksi menggunakan HOG (Lau et al., 2025)

def ekstraksi_hog(images_hog, orientations=9, pixels_per_cell=(8, 8),
                  cells_per_block=(2, 2)):
    """
    Mengekstraksi fitur HOG (Histogram of Oriented Gradients) dari
    setiap gambar. HOG menangkap informasi bentuk dan tepi objek
    (Lau et al., 2025; Ochango et al., 2022).

    Args:
        images_hog : array gambar (N, H, W, 3) uint8
        orientations, pixels_per_cell, cells_per_block : parameter HOG

    Returns:
        features : array (N, d) fitur HOG
    """
    print("\n[FITUR] Mengekstraksi fitur HOG ...")
    features = []
    for img in images_hog:
        # Konversi ke grayscale untuk HOG
        img_gray = cv2.cvtColor(img, cv2.COLOR_RGB2GRAY)
        feat = hog(
            img_gray,
            orientations=orientations,
            pixels_per_cell=pixels_per_cell,
            cells_per_block=cells_per_block,
            visualize=False,
            feature_vector=True)
        features.append(feat)
    features = np.array(features, dtype=np.float32)
    print(f"  Dimensi fitur HOG: {features.shape}")
    return features


# ===========================================================================
# BAGIAN E: PEMBAGIAN DATA
# ===========================================================================
# Rasio 70:20:10 sesuai Haqqi et al. (2024)

def bagi_data(images_cnn, features_hog, labels, label_enc, config):
    """
    Membagi data menjadi tiga subset: train, validasi, dan test.
    Stratified split digunakan agar distribusi kelas seimbang.

    Rasio: 70% train · 20% validasi · 10% test
    (Haqqi et al., 2024)
    """
    labels_int = label_enc.transform(labels)
    rs = config["RANDOM_STATE"]

    # Split pertama: pisahkan test (10%)
    X_cnn_tv, X_cnn_test, X_hog_tv, X_hog_test, y_tv, y_test = \
        train_test_split(images_cnn, features_hog, labels_int,
                         test_size=config["TEST_RATIO"],
                         stratify=labels_int,
                         random_state=rs)

    # Split kedua: pisahkan validasi dari sisa (20/90 ≈ 22.2%)
    val_ratio_adj = config["VAL_RATIO"] / (1.0 - config["TEST_RATIO"])
    X_cnn_train, X_cnn_val, X_hog_train, X_hog_val, y_train, y_val = \
        train_test_split(X_cnn_tv, X_hog_tv, y_tv,
                         test_size=val_ratio_adj,
                         stratify=y_tv,
                         random_state=rs)

    # Standarisasi fitur HOG (penting untuk SVM)
    scaler = StandardScaler()
    X_hog_train = scaler.fit_transform(X_hog_train)
    X_hog_val   = scaler.transform(X_hog_val)
    X_hog_test  = scaler.transform(X_hog_test)

    print("\n[SPLIT] Pembagian data:")
    print(f"  Train      : {len(y_train):>5} sampel ({len(y_train)/len(labels)*100:.1f}%)")
    print(f"  Validasi   : {len(y_val):>5} sampel ({len(y_val)/len(labels)*100:.1f}%)")
    print(f"  Test       : {len(y_test):>5} sampel ({len(y_test)/len(labels)*100:.1f}%)")

    return (X_cnn_train, X_cnn_val, X_cnn_test,
            X_hog_train, X_hog_val, X_hog_test,
            y_train, y_val, y_test, scaler)


# ===========================================================================
# BAGIAN F: TRAINING MODEL
# ===========================================================================

# ---------------------------------------------------------------------------
# F1. Model CNN
# ---------------------------------------------------------------------------
# Arsitektur berbasis Haqqi et al. (2024): konvolusi → aktivasi → pooling →
# fully connected → softmax. Dimodifikasi dengan tambahan Batch Normalization
# dan Dropout untuk regularisasi.

def bangun_model_cnn(num_kelas, img_size, dropout_rate, learning_rate):
    """
    Membangun arsitektur CNN untuk klasifikasi gambar sampah.

    Arsitektur (Haqqi et al., 2024):
      - Conv2D (32 filter, 3x3) → BatchNorm → ReLU → MaxPool
      - Conv2D (64 filter, 3x3) → BatchNorm → ReLU → MaxPool
      - Conv2D (128 filter, 3x3) → BatchNorm → ReLU → MaxPool
      - GlobalAveragePooling
      - Dense (256) → Dropout → Dense (num_kelas) → Softmax
    """
    model = keras.Sequential([
        # --- Blok 1 ---
        layers.Conv2D(32, (3, 3), padding='same',
                      input_shape=(*img_size, 3)),
        layers.BatchNormalization(),
        layers.Activation('relu'),
        layers.MaxPooling2D(2, 2),

        # --- Blok 2 ---
        layers.Conv2D(64, (3, 3), padding='same'),
        layers.BatchNormalization(),
        layers.Activation('relu'),
        layers.MaxPooling2D(2, 2),

        # --- Blok 3 ---
        layers.Conv2D(128, (3, 3), padding='same'),
        layers.BatchNormalization(),
        layers.Activation('relu'),
        layers.MaxPooling2D(2, 2),

        # --- Blok 4 ---
        layers.Conv2D(256, (3, 3), padding='same'),
        layers.BatchNormalization(),
        layers.Activation('relu'),
        layers.MaxPooling2D(2, 2),

        # --- Klasifikasi ---
        layers.GlobalAveragePooling2D(),
        layers.Dense(256, activation='relu'),
        layers.Dropout(dropout_rate),
        layers.Dense(num_kelas, activation='softmax'),
    ], name="CNN_Klasifikasi_Sampah")

    model.compile(
        optimizer=keras.optimizers.Adam(learning_rate=learning_rate),
        loss='sparse_categorical_crossentropy',
        metrics=['accuracy']
    )
    return model


def latih_cnn(X_train, y_train, X_val, y_val, config):
    """
    Melatih model CNN dengan callbacks EarlyStopping dan ReduceLROnPlateau.
    Data augmentasi diterapkan pada data pelatihan.
    """
    print("\n" + "="*50)
    print("[CNN] Memulai pelatihan ...")
    print("="*50)

    model = bangun_model_cnn(
        NUM_KELAS,
        config["IMG_SIZE"],
        config["DROPOUT_RATE"],
        config["LEARNING_RATE"]
    )
    model.summary()

    # Augmentasi data (Haqqi et al., 2024): horizontal flip, rotation, zoom
    datagen = ImageDataGenerator(
        rotation_range=20,
        width_shift_range=0.15,
        height_shift_range=0.15,
        horizontal_flip=True,
        zoom_range=0.15,
        brightness_range=[0.8, 1.2],
    )

    cb_list = [
        callbacks.EarlyStopping(monitor='val_accuracy', patience=10,
                                restore_best_weights=True, verbose=1),
        callbacks.ReduceLROnPlateau(monitor='val_loss', factor=0.5,
                                    patience=5, verbose=1, min_lr=1e-6),
        callbacks.ModelCheckpoint(
            filepath=os.path.join(config["OUTPUT_DIR"], "best_cnn.h5"),
            monitor='val_accuracy', save_best_only=True, verbose=0
        ),
    ]

    history = model.fit(
        datagen.flow(X_train, y_train, batch_size=config["BATCH_SIZE"]),
        steps_per_epoch=len(X_train) // config["BATCH_SIZE"],
        validation_data=(X_val, y_val),
        epochs=config["EPOCHS"],
        callbacks=cb_list,
        verbose=1
    )

    return model, history


# ---------------------------------------------------------------------------
# F2. Model SVM
# ---------------------------------------------------------------------------
# Yulita et al. (2023): kernel RBF memberikan performa terbaik (F1=0.874)
# dibanding kernel linear dan sigmoid.

def latih_svm(X_train, y_train, config):
    """
    Melatih Support Vector Machine dengan kernel RBF.

    Parameter (Yulita et al., 2023):
      - kernel : 'rbf' (Radial Basis Function)
      - C      : 10.0  (parameter regulasi)
      - gamma  : 'scale'
    """
    print("\n" + "="*50)
    print("[SVM] Memulai pelatihan ...")
    print("="*50)

    model_svm = SVC(
        kernel=config["SVM_KERNEL"],
        C=config["SVM_C"],
        gamma=config["SVM_GAMMA"],
        probability=True,
        random_state=config["RANDOM_STATE"]
    )
    model_svm.fit(X_train, y_train)
    print("  SVM selesai dilatih.")
    return model_svm


# ---------------------------------------------------------------------------
# F3. Model Decision Tree
# ---------------------------------------------------------------------------
# Jijo & Abdulazeez (2021): Decision Tree menggunakan Gini Index (CART)
# atau Entropy (ID3/C4.5) sebagai kriteria pemisahan.

def latih_decision_tree(X_train, y_train, config):
    """
    Melatih Decision Tree Classifier.

    Parameter (Jijo & Abdulazeez, 2021):
      - criterion : 'gini' (CART) atau 'entropy' (ID3/C4.5)
      - max_depth : None (tumbuh penuh)
    """
    print("\n" + "="*50)
    print("[DT]  Memulai pelatihan ...")
    print("="*50)

    model_dt = DecisionTreeClassifier(
        criterion=config["DT_CRITERION"],
        max_depth=config["DT_MAX_DEPTH"],
        random_state=config["RANDOM_STATE"]
    )
    model_dt.fit(X_train, y_train)
    print(f"  Decision Tree selesai. Kedalaman pohon: {model_dt.get_depth()}")
    return model_dt


# ---------------------------------------------------------------------------
# F4. Model Random Forest
# ---------------------------------------------------------------------------
# Lau et al. (2025): n_estimators=150 memberikan generalisasi yang baik.
# Random Forest adalah ensemble learning yang menggabungkan banyak Decision
# Tree melalui majority voting.

def latih_random_forest(X_train, y_train, config):
    """
    Melatih Random Forest Classifier.

    Parameter (Lau et al., 2025):
      - n_estimators : 150 pohon keputusan
      - max_depth    : None
      - random_state : 42
    """
    print("\n" + "="*50)
    print("[RF]  Memulai pelatihan ...")
    print("="*50)

    model_rf = RandomForestClassifier(
        n_estimators=config["RF_N_ESTIMATORS"],
        max_depth=config["RF_MAX_DEPTH"],
        random_state=config["RF_RANDOM_STATE"],
        n_jobs=-1  # gunakan semua core CPU
    )
    model_rf.fit(X_train, y_train)
    print("  Random Forest selesai dilatih.")
    return model_rf


# ===========================================================================
# BAGIAN G: EVALUASI MODEL
# ===========================================================================

def evaluasi_model(nama, model, X_test, y_test, label_enc,
                   is_cnn=False, output_dir="./output_model"):
    """
    Menghitung akurasi, menampilkan classification report, dan
    menyimpan confusion matrix untuk satu model.

    Returns:
        dict berisi akurasi dan metrik lainnya
    """
    print(f"\n--- Evaluasi: {nama} ---")

    if is_cnn:
        y_pred_prob = model.predict(X_test)
        y_pred      = np.argmax(y_pred_prob, axis=1)
    else:
        y_pred = model.predict(X_test)

    akurasi = accuracy_score(y_test, y_pred)
    report  = classification_report(y_test, y_pred,
                                     target_names=label_enc.classes_,
                                     output_dict=True)
    cm      = confusion_matrix(y_test, y_pred)

    print(f"  Akurasi : {akurasi*100:.2f}%")
    print(classification_report(y_test, y_pred,
                                 target_names=label_enc.classes_))

    # Simpan confusion matrix sebagai gambar
    fig, ax = plt.subplots(figsize=(8, 6))
    disp = ConfusionMatrixDisplay(confusion_matrix=cm,
                                   display_labels=label_enc.classes_)
    disp.plot(ax=ax, colorbar=True, cmap='Blues')
    ax.set_title(f"Confusion Matrix — {nama}", fontsize=13, pad=12)
    plt.tight_layout()
    cm_path = os.path.join(output_dir, f"cm_{nama.replace(' ', '_')}.png")
    plt.savefig(cm_path, dpi=150)
    plt.close()
    print(f"  Confusion matrix disimpan: {cm_path}")

    return {
        "nama"     : nama,
        "akurasi"  : akurasi,
        "presisi"  : report["weighted avg"]["precision"],
        "recall"   : report["weighted avg"]["recall"],
        "f1_score" : report["weighted avg"]["f1-score"],
        "cm"       : cm,
    }


# ===========================================================================
# BAGIAN H: VISUALISASI OUTPUT
# ===========================================================================

def plot_training_cnn(history, output_dir):
    """Grafik akurasi dan loss pelatihan CNN (per epoch)."""
    fig, axes = plt.subplots(1, 2, figsize=(14, 5))

    # --- Akurasi ---
    axes[0].plot(history.history['accuracy'],     label='Train', color='#2196F3')
    axes[0].plot(history.history['val_accuracy'], label='Validasi', color='#FF5722')
    axes[0].set_title("Akurasi Pelatihan CNN", fontsize=13)
    axes[0].set_xlabel("Epoch")
    axes[0].set_ylabel("Akurasi")
    axes[0].legend()
    axes[0].grid(alpha=0.3)

    # --- Loss ---
    axes[1].plot(history.history['loss'],     label='Train', color='#2196F3')
    axes[1].plot(history.history['val_loss'], label='Validasi', color='#FF5722')
    axes[1].set_title("Loss Pelatihan CNN", fontsize=13)
    axes[1].set_xlabel("Epoch")
    axes[1].set_ylabel("Loss")
    axes[1].legend()
    axes[1].grid(alpha=0.3)

    plt.suptitle("Grafik Pelatihan CNN — Klasifikasi Sampah",
                 fontsize=14, fontweight='bold', y=1.02)
    plt.tight_layout()
    path = os.path.join(output_dir, "training_cnn.png")
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"\n[VIS] Grafik CNN disimpan: {path}")


def plot_perbandingan_model(hasil_list, output_dir):
    """
    Grafik batang perbandingan akurasi, presisi, recall, dan F1-score
    untuk keempat model.
    """
    model_names = [h["nama"] for h in hasil_list]
    metrik_keys = ["akurasi", "presisi", "recall", "f1_score"]
    metrik_label = ["Akurasi", "Presisi", "Recall", "F1-Score"]
    colors = ['#2196F3', '#4CAF50', '#FF9800', '#E91E63']

    x = np.arange(len(metrik_keys))
    width = 0.18

    fig, ax = plt.subplots(figsize=(12, 6))
    for i, hasil in enumerate(hasil_list):
        vals = [hasil[k] for k in metrik_keys]
        bars = ax.bar(x + i * width, vals, width,
                      label=hasil["nama"], color=colors[i], alpha=0.85)
        for bar, v in zip(bars, vals):
            ax.text(bar.get_x() + bar.get_width() / 2,
                    bar.get_height() + 0.005,
                    f"{v*100:.1f}%",
                    ha='center', va='bottom', fontsize=8)

    ax.set_xticks(x + width * 1.5)
    ax.set_xticklabels(metrik_label, fontsize=12)
    ax.set_ylabel("Skor", fontsize=12)
    ax.set_ylim(0, 1.12)
    ax.set_title("Perbandingan Performa Model Klasifikasi Sampah",
                 fontsize=14, fontweight='bold', pad=12)
    ax.legend(loc='lower right', fontsize=10)
    ax.grid(axis='y', alpha=0.3)

    plt.tight_layout()
    path = os.path.join(output_dir, "perbandingan_model.png")
    plt.savefig(path, dpi=150)
    plt.close()
    print(f"[VIS] Grafik perbandingan disimpan: {path}")


def plot_semua_confusion_matrix(hasil_list, label_enc, output_dir):
    """Tampilkan keempat confusion matrix dalam satu figure."""
    fig, axes = plt.subplots(2, 2, figsize=(16, 14))
    axes = axes.flatten()

    for i, hasil in enumerate(hasil_list):
        disp = ConfusionMatrixDisplay(confusion_matrix=hasil["cm"],
                                       display_labels=label_enc.classes_)
        disp.plot(ax=axes[i], colorbar=False, cmap='Blues')
        axes[i].set_title(f"{hasil['nama']} — Akurasi: {hasil['akurasi']*100:.2f}%",
                           fontsize=11, pad=8)
        axes[i].tick_params(axis='x', rotation=45)

    plt.suptitle("Confusion Matrix Semua Model", fontsize=14,
                 fontweight='bold', y=1.01)
    plt.tight_layout()
    path = os.path.join(output_dir, "semua_confusion_matrix.png")
    plt.savefig(path, dpi=150, bbox_inches='tight')
    plt.close()
    print(f"[VIS] Semua confusion matrix disimpan: {path}")


# ===========================================================================
# BAGIAN I: PREDIKSI GAMBAR BARU
# ===========================================================================

def prediksi_gambar_baru(path_gambar, model_cnn, model_svm,
                          model_dt, model_rf, scaler, label_enc, config):
    """
    Menerima path gambar baru dan menampilkan prediksi dari keempat model.

    Args:
        path_gambar : path ke file gambar (.jpg/.png)
        ...
    """
    print(f"\n[PREDIKSI] Gambar: {path_gambar}")

    img_bgr = cv2.imread(str(path_gambar))
    if img_bgr is None:
        print("  ERROR: Gambar tidak dapat dibaca.")
        return

    img_rgb      = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    img_filtered = cv2.GaussianBlur(img_rgb, (3, 3), 0)

    # Persiapan untuk CNN
    img_cnn = cv2.resize(img_filtered, (config["IMG_SIZE"][1], config["IMG_SIZE"][0]))
    img_cnn = img_cnn.astype(np.float32) / 255.0
    img_cnn_batch = np.expand_dims(img_cnn, axis=0)

    # Persiapan untuk HOG
    img_hog_raw = cv2.resize(img_filtered,
                              (config["IMG_SIZE_HOG"][1], config["IMG_SIZE_HOG"][0]))
    img_gray    = cv2.cvtColor(img_hog_raw, cv2.COLOR_RGB2GRAY)
    feat        = hog(img_gray, orientations=9,
                      pixels_per_cell=(8, 8), cells_per_block=(2, 2),
                      visualize=False, feature_vector=True)
    feat_scaled = scaler.transform([feat])

    # Prediksi
    pred_cnn = label_enc.inverse_transform([np.argmax(model_cnn.predict(img_cnn_batch))])[0]
    pred_svm = label_enc.inverse_transform(model_svm.predict(feat_scaled))[0]
    pred_dt  = label_enc.inverse_transform(model_dt.predict(feat_scaled))[0]
    pred_rf  = label_enc.inverse_transform(model_rf.predict(feat_scaled))[0]

    # Tampilkan gambar + prediksi
    fig, axes = plt.subplots(1, 2, figsize=(10, 5))
    axes[0].imshow(img_rgb)
    axes[0].set_title("Gambar Input", fontsize=12)
    axes[0].axis('off')

    info = (f"Prediksi Model:\n"
            f"  CNN          : {pred_cnn}\n"
            f"  SVM (RBF)    : {pred_svm}\n"
            f"  Decision Tree: {pred_dt}\n"
            f"  Random Forest: {pred_rf}")
    axes[1].text(0.1, 0.5, info,
                 transform=axes[1].transAxes,
                 fontsize=13, verticalalignment='center',
                 fontfamily='monospace',
                 bbox=dict(boxstyle='round', facecolor='#f0f4ff', alpha=0.8))
    axes[1].axis('off')
    axes[1].set_title("Hasil Klasifikasi", fontsize=12)

    plt.suptitle("Prediksi Gambar Baru — Klasifikasi Sampah",
                 fontsize=14, fontweight='bold')
    plt.tight_layout()
    out_path = os.path.join(CONFIG["OUTPUT_DIR"], "prediksi_gambar_baru.png")
    plt.savefig(out_path, dpi=150)
    plt.show()
    print(f"  Prediksi disimpan: {out_path}")

    return {"CNN": pred_cnn, "SVM": pred_svm,
            "Decision Tree": pred_dt, "Random Forest": pred_rf}


# ===========================================================================
# BAGIAN J: SIMPAN MODEL
# ===========================================================================

def simpan_semua_model(model_cnn, model_svm, model_dt, model_rf,
                        scaler, label_enc, output_dir):
    """
    Menyimpan semua model yang sudah dilatih.
    - CNN         → format .h5 (Keras)
    - SVM, DT, RF → format .pkl (Pickle / Scikit-learn)
    - Scaler      → .pkl
    - LabelEncoder→ .pkl
    """
    # CNN
    cnn_path = os.path.join(output_dir, "model_cnn.h5")
    model_cnn.save(cnn_path)
    print(f"\n[SIMPAN] CNN    : {cnn_path}")

    # ML models
    for nama, obj in [("svm", model_svm), ("dt", model_dt),
                       ("rf", model_rf), ("scaler", scaler),
                       ("label_enc", label_enc)]:
        path = os.path.join(output_dir, f"model_{nama}.pkl")
        with open(path, "wb") as f:
            pickle.dump(obj, f)
        print(f"[SIMPAN] {nama.upper():<9}: {path}")


# ===========================================================================
# BAGIAN K: ANALISIS PERBANDINGAN MODEL
# ===========================================================================

def analisis_perbandingan(hasil_list, output_dir):
    """
    Mencetak tabel perbandingan performa dan analisis teks
    berdasarkan tinjauan literatur.
    """
    print("\n" + "=" * 60)
    print("  ANALISIS PERBANDINGAN MODEL")
    print("=" * 60)

    df = pd.DataFrame(hasil_list)[["nama", "akurasi", "presisi", "recall", "f1_score"]]
    df.columns = ["Model", "Akurasi", "Presisi", "Recall", "F1-Score"]
    for col in ["Akurasi", "Presisi", "Recall", "F1-Score"]:
        df[col] = df[col].map(lambda v: f"{v*100:.2f}%")
    print(df.to_string(index=False))

    # Cari model terbaik
    terbaik = max(hasil_list, key=lambda h: h["akurasi"])
    terburuk = min(hasil_list, key=lambda h: h["akurasi"])
    print(f"\n  Model terbaik  : {terbaik['nama']} "
          f"({terbaik['akurasi']*100:.2f}%)")
    print(f"  Model terendah : {terburuk['nama']} "
          f"({terburuk['akurasi']*100:.2f}%)")

    analisis_text = f"""
PEMBAHASAN PERBANDINGAN MODEL
==============================
Penelitian ini membandingkan empat model machine learning untuk
klasifikasi gambar sampah, mengacu pada literatur berikut:

1. CNN (Convolutional Neural Network)
   Haqqi et al. (2024) melaporkan akurasi 95% menggunakan CNN
   dengan 2.848 gambar dan 6 kelas. Penelitian ini mereplikasi
   arsitektur tersebut dengan tambahan Batch Normalization dan
   Global Average Pooling untuk regularisasi lebih baik.

2. SVM (Support Vector Machine)
   Yulita et al. (2023) menemukan bahwa kombinasi Inception-V3
   sebagai ekstraktor fitur dan SVM kernel RBF menghasilkan F1-score
   0.874, melampaui Decision Tree (0.585) dan Random Forest (0.689).
   Pada penelitian ini, HOG digunakan sebagai alternatif ekstraktor
   fitur yang lebih ringan secara komputasi.

3. Decision Tree
   Jijo & Abdulazeez (2021) merangkum berbagai studi Decision Tree
   dengan akurasi 83.3%–99.93% tergantung dataset. Decision Tree
   rentan terhadap overfitting karena pohon yang terlalu dalam.

4. Random Forest
   Lau et al. (2025) mencapai akurasi 96% menggunakan Random Forest
   + HOG dengan dataset organik vs. anorganik. Ensemble 150 pohon
   mengurangi variansi dan meningkatkan stabilitas prediksi.

KELEBIHAN DAN KEKURANGAN:
  CNN           : (+) Akurasi tinggi, ekstraksi fitur otomatis
                  (-) Membutuhkan GPU dan data besar
  SVM           : (+) Efektif pada fitur berdimensi tinggi
                  (-) Lambat pada dataset sangat besar
  Decision Tree : (+) Mudah diinterpretasi, cepat dilatih
                  (-) Rentan overfitting
  Random Forest : (+) Stabil, tahan overfitting
                  (-) Kurang interpretatif dibanding DT tunggal

Model terbaik: {terbaik['nama']} dengan akurasi {terbaik['akurasi']*100:.2f}%
"""
    print(analisis_text)

    # Simpan ke file teks
    with open(os.path.join(output_dir, "analisis_perbandingan.txt"), "w",
              encoding="utf-8") as f:
        f.write(analisis_text)

    return df


# ===========================================================================
# BAGIAN L: MAIN — MENJALANKAN SELURUH PIPELINE
# ===========================================================================

def main():
    print("\n" + "=" * 60)
    print("  MEMULAI PIPELINE")
    print("=" * 60)

    # 1. Load & Preprocessing
    images_cnn, images_hog, labels, label_enc = load_and_preprocess_dataset(
        CONFIG["DATASET_DIR"],
        CONFIG["IMG_SIZE"],
        CONFIG["IMG_SIZE_HOG"]
    )

    # 2. Ekstraksi Fitur HOG (untuk ML klasik)
    features_hog = ekstraksi_hog(images_hog)

    # 3. Pembagian Data
    (X_cnn_train, X_cnn_val, X_cnn_test,
     X_hog_train, X_hog_val, X_hog_test,
     y_train, y_val, y_test, scaler) = bagi_data(
        images_cnn, features_hog, labels, label_enc, CONFIG
    )

    # 4. Pelatihan Model
    print("\n" + "=" * 60)
    print("  PELATIHAN MODEL")
    print("=" * 60)

    model_cnn, history = latih_cnn(
        X_cnn_train, y_train, X_cnn_val, y_val, CONFIG
    )
    model_svm = latih_svm(X_hog_train, y_train, CONFIG)
    model_dt  = latih_decision_tree(X_hog_train, y_train, CONFIG)
    model_rf  = latih_random_forest(X_hog_train, y_train, CONFIG)

    # 5. Evaluasi
    print("\n" + "=" * 60)
    print("  EVALUASI MODEL")
    print("=" * 60)

    hasil_list = [
        evaluasi_model("CNN", model_cnn, X_cnn_test, y_test,
                        label_enc, is_cnn=True,
                        output_dir=CONFIG["OUTPUT_DIR"]),
        evaluasi_model("SVM RBF", model_svm, X_hog_test, y_test,
                        label_enc, output_dir=CONFIG["OUTPUT_DIR"]),
        evaluasi_model("Decision Tree", model_dt, X_hog_test, y_test,
                        label_enc, output_dir=CONFIG["OUTPUT_DIR"]),
        evaluasi_model("Random Forest", model_rf, X_hog_test, y_test,
                        label_enc, output_dir=CONFIG["OUTPUT_DIR"]),
    ]

    # 6. Visualisasi
    plot_training_cnn(history, CONFIG["OUTPUT_DIR"])
    plot_perbandingan_model(hasil_list, CONFIG["OUTPUT_DIR"])
    plot_semua_confusion_matrix(hasil_list, label_enc, CONFIG["OUTPUT_DIR"])

    # 7. Analisis Perbandingan
    analisis_perbandingan(hasil_list, CONFIG["OUTPUT_DIR"])

    # 8. Simpan Model
    simpan_semua_model(model_cnn, model_svm, model_dt, model_rf,
                        scaler, label_enc, CONFIG["OUTPUT_DIR"])

    # 9. Prediksi gambar baru (opsional — ubah path sesuai gambar Anda)
    # contoh_gambar = "./contoh_plastik.jpg"
    # if os.path.exists(contoh_gambar):
    #     prediksi_gambar_baru(
    #         contoh_gambar, model_cnn, model_svm, model_dt, model_rf,
    #         scaler, label_enc, CONFIG
    #     )

    print("\n" + "=" * 60)
    print("  PIPELINE SELESAI")
    print(f"  Output tersimpan di: {CONFIG['OUTPUT_DIR']}/")
    print("=" * 60)


# ===========================================================================
# ENTRY POINT
# ===========================================================================
if __name__ == "__main__":
    main()


# ===========================================================================
# CARA PENGGUNAAN
# ===========================================================================
# 1. Install dependensi:
#    pip install tensorflow scikit-learn scikit-image opencv-python
#                matplotlib seaborn pandas numpy
#
# 2. Unduh dataset Kaggle:
#    kaggle datasets download -d asdasdasasdas/garbage-classification
#    unzip garbage-classification.zip
#
# 3. Sesuaikan CONFIG["DATASET_DIR"] dengan lokasi folder dataset
#
# 4. Jalankan:
#    python klasifikasi_sampah_pipeline.py
#
# 5. Output tersimpan di ./output_model/ berupa:
#    - model_cnn.h5
#    - model_svm.pkl, model_dt.pkl, model_rf.pkl
#    - training_cnn.png
#    - perbandingan_model.png
#    - semua_confusion_matrix.png
#    - analisis_perbandingan.txt
# ===========================================================================

"""# **Testing**"""

# Install library tambahan jika belum ada
!pip install scikit-image -q

import os, pickle, warnings
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
import cv2
from skimage.feature import hog
from google.colab import files
import tensorflow as tf

warnings.filterwarnings('ignore')
print('✅ Library siap!')

import os, pickle, warnings
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.gridspec as gridspec
import cv2
from skimage.feature import hog
from google.colab import files
import tensorflow as tf

warnings.filterwarnings('ignore')
print('✅ Library siap!')


# ─── PATH MODEL ─────────────────────────────────────────────────────────────
# Sesuaikan path ini jika model disimpan di lokasi berbeda
MODEL_DIR = '/content/output_model'
DATA_DIR  = '/content/dataset/Data/Garbage_Classification'

# ─── KONFIGURASI ────────────────────────────────────────────────────────────
# KELAS harus sesuai dengan KELAS yang digunakan saat pelatihan (7 kelas)
KELAS = ["Battery", "Cardboard", "Clothes", "Glass", "Metal", "Paper", "Plastic"]

# Emoji dan warna tiap kelas (harus sesuai dengan KELAS di atas)
INFO_KELAS = {
    'Battery':   {'emoji': '🔋', 'label': 'Baterai',       'warna': '#757575', 'tips': 'Buang ke tempat khusus baterai atau daur ulang'},
    'Cardboard': {'emoji': '📦', 'label': 'Karton / Kardus', 'warna': '#8B6914', 'tips': 'Lipat dan buang ke tempat sampah daur ulang'},
    'Clothes':   {'emoji': '👕', 'label': 'Pakaian',       'warna': '#673AB7', 'tips': 'Donasikan atau daur ulang di tempat khusus tekstil'},
    'Glass':     {'emoji': '🍶', 'label': 'Kaca / Gelas',    'warna': '#00BCD4', 'tips': 'Bungkus dengan kertas agar tidak melukai'},
    'Metal':     {'emoji': '🔩', 'label': 'Logam / Metal',   'warna': '#607D8B', 'tips': 'Serahkan ke bank sampah atau pengepul'},
    'Paper':     {'emoji': '📄', 'label': 'Kertas',        'warna': '#FF9800', 'tips': 'Pisahkan dari bahan basah sebelum didaur ulang'},
    'Plastic':   {'emoji': '🧴', 'label': 'Plastik',       'warna': '#E91E63', 'tips': 'Cuci bersih sebelum dibuang ke tempat daur ulang'},
}

IMG_SIZE_CNN = (224, 224)
IMG_SIZE_HOG = (64, 64)

# ─── MUAT MODEL ─────────────────────────────────────────────────────────────
print('Memuat model...')

try:
    model_cnn = tf.keras.models.load_model(f'{MODEL_DIR}/model_cnn.h5')
    print('  ✅ CNN dimuat')
except Exception as e:
    model_cnn = None
    print(f'  ⚠️  CNN gagal dimuat: {e}')

try:
    with open(f'{MODEL_DIR}/model_svm.pkl', 'rb') as f:
        model_svm = pickle.load(f)
    print('  ✅ SVM dimuat')
except Exception as e:
    model_svm = None
    print(f'  ⚠️  SVM gagal dimuat: {e}')

try:
    with open(f'{MODEL_DIR}/model_dt.pkl', 'rb') as f:
        model_dt = pickle.load(f)
    print('  ✅ Decision Tree dimuat')
except Exception as e:
    model_dt = None
    print(f'  ⚠️  Decision Tree gagal dimuat: {e}')

try:
    with open(f'{MODEL_DIR}/model_rf.pkl', 'rb') as f:
        model_rf = pickle.load(f)
    print('  ✅ Random Forest dimuat')
except Exception as e:
    model_rf = None
    print(f'  ⚠️  Random Forest gagal dimuat: {e}')

try:
    with open(f'{MODEL_DIR}/model_scaler.pkl', 'rb') as f:
        scaler = pickle.load(f)
    print('  ✅ Scaler dimuat')
except Exception as e:
    scaler = None
    print(f'  ⚠️  Scaler gagal dimuat: {e}')

try:
    with open(f'{MODEL_DIR}/model_label_enc.pkl', 'rb') as f:
        label_enc = pickle.load(f)
    print('  ✅ LabelEncoder dimuat')
except Exception as e:
    label_enc = None
    print(f'  ⚠️  LabelEncoder gagal dimuat: {e}')


print('\n Model siap digunakan!')

def preprocess_gambar(path_gambar):
    """Baca gambar dan siapkan untuk CNN dan HOG."""
    img_bgr     = cv2.imread(path_gambar)
    img_rgb     = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    img_filter  = cv2.GaussianBlur(img_rgb, (3, 3), 0)

    # Untuk CNN — 224x224, normalisasi 0–1
    img_cnn = cv2.resize(img_filter, (IMG_SIZE_CNN[1], IMG_SIZE_CNN[0]))
    img_cnn = img_cnn.astype(np.float32) / 255.0
    img_cnn = np.expand_dims(img_cnn, axis=0)

    # Untuk HOG — 64x64, ekstraksi fitur
    img_hog  = cv2.resize(img_filter, (IMG_SIZE_HOG[1], IMG_SIZE_HOG[0]))
    img_gray = cv2.cvtColor(img_hog, cv2.COLOR_RGB2GRAY)
    fitur    = hog(img_gray, orientations=9,
                   pixels_per_cell=(8, 8), cells_per_block=(2, 2),
                   visualize=False, feature_vector=True)
    fitur    = scaler.transform([fitur]) if scaler else fitur.reshape(1, -1)

    return img_rgb, img_cnn, fitur


def prediksi_semua(path_gambar):
    """Jalankan prediksi dari keempat model dan kembalikan hasilnya."""
    img_asli, img_cnn, fitur = preprocess_gambar(path_gambar)
    hasil = {}

    # SVM
    if model_svm:
        idx = model_svm.predict(fitur)[0]
        prob = model_svm.predict_proba(fitur)[0]
        hasil['SVM RBF'] = {'kelas': KELAS[idx], 'prob': prob, 'confidence': prob[idx]}

    # Random Forest
    if model_rf:
        idx = model_rf.predict(fitur)[0]
        prob = model_rf.predict_proba(fitur)[0]
        hasil['Random Forest'] = {'kelas': KELAS[idx], 'prob': prob, 'confidence': prob[idx]}

    # Decision Tree
    if model_dt:
        idx = model_dt.predict(fitur)[0]
        prob = model_dt.predict_proba(fitur)[0]
        hasil['Decision Tree'] = {'kelas': KELAS[idx], 'prob': prob, 'confidence': prob[idx]}

    # CNN
    if model_cnn:
        prob = model_cnn.predict(img_cnn, verbose=0)[0]
        idx  = np.argmax(prob)
        hasil['CNN'] = {'kelas': KELAS[idx], 'prob': prob, 'confidence': prob[idx]}

    return img_asli, hasil


def tampilkan_hasil(img_asli, hasil, nama_file):
    """Tampilkan gambar + hasil klasifikasi dalam satu figure yang informatif."""

    # Tentukan prediksi mayoritas (voting)
    votes = [v['kelas'] for v in hasil.values()]
    from collections import Counter
    kelas_mayoritas = Counter(votes).most_common(1)[0][0]
    info = INFO_KELAS[kelas_mayoritas]

    # ── LAYOUT FIGURE ───────────────────────────────────────────────────────
    fig = plt.figure(figsize=(18, 11), facecolor='#F8F9FA')
    gs  = gridspec.GridSpec(
        3, 3,
        figure=fig,
        hspace=0.45, wspace=0.35,
        left=0.04, right=0.97, top=0.88, bottom=0.05
    )

    # ── JUDUL UTAMA ─────────────────────────────────────────────────────────
    fig.suptitle(
        f'Sistem Klasifikasi Sampah Otomatis',
        fontsize=20, fontweight='bold', color='#1A1A2E', y=0.97
    )

    # ══════════════════════════════════════════════════════════════════════════
    # PANEL KIRI — Gambar asli + banner hasil
    # ══════════════════════════════════════════════════════════════════════════
    ax_img = fig.add_subplot(gs[0:2, 0])
    ax_img.imshow(img_asli)
    ax_img.axis('off')

    # Border berwarna sesuai kelas
    for spine in ax_img.spines.values():
        spine.set_visible(True)
        spine.set_color(info['warna'])
        spine.set_linewidth(4)

    ax_img.set_title(
        f'{os.path.basename(nama_file)}',
        fontsize=11, color='#555555', pad=8
    )

    # Banner HASIL MAYORITAS di bawah gambar
    ax_banner = fig.add_subplot(gs[2, 0])
    ax_banner.set_facecolor(info['warna'])
    ax_banner.set_xlim(0, 1)
    ax_banner.set_ylim(0, 1)
    ax_banner.axis('off')

    ax_banner.text(
        0.5, 0.72,
        f"{info['emoji']}  {info['label'].upper()}",
        ha='center', va='center',
        fontsize=16, fontweight='bold', color='white'
    )
    ax_banner.text(
        0.5, 0.35,
        f" {info['tips']}",
        ha='center', va='center',
        fontsize=9, color='white', style='italic',
        wrap=True
    )
    ax_banner.text(
        0.5, 0.10,
        '★ Prediksi Mayoritas Model',
        ha='center', va='center',
        fontsize=8, color='#FFFFFFAA'
    )

    # ══════════════════════════════════════════════════════════════════════════
    # PANEL TENGAH & KANAN — Kartu tiap model
    # ══════════════════════════════════════════════════════════════════════════
    posisi = [(0, 1), (0, 2), (1, 1), (1, 2)]
    model_urutan = ['SVM RBF', 'Random Forest', 'Decision Tree', 'CNN']

    for (baris, kolom), nama_model in zip(posisi, model_urutan):
        if nama_model not in hasil:
            continue

        data   = hasil[nama_model]
        kelas  = data['kelas']
        conf   = data['confidence']
        prob   = data['prob']
        inf    = INFO_KELAS[kelas]

        ax_card = fig.add_subplot(gs[baris, kolom])
        ax_card.set_facecolor('#FFFFFF')

        # Header kartu
        ax_card.axhspan(
            len(KELAS) + 0.5, len(KELAS) + 1.8,
            facecolor=inf['warna'], alpha=0.90
        )
        ax_card.text(
            -0.3, len(KELAS) + 1.15,
            f'{nama_model}',
            fontsize=10, fontweight='bold', color='white', va='center'
        )
        ax_card.text(
            5.8, len(KELAS) + 1.15,
            f'{conf*100:.1f}%',
            fontsize=10, fontweight='bold', color='white',
            va='center', ha='right'
        )

        # Bar chart probabilitas tiap kelas
        y_pos = np.arange(len(KELAS))
        warna_bar = [
            INFO_KELAS[k]['warna'] if k == kelas else '#D0D0D0'
            for k in KELAS
        ]

        bars = ax_card.barh(
            y_pos, prob * 100,
            color=warna_bar,
            edgecolor='white',
            linewidth=0.5,
            height=0.65
        )

        # Label nama kelas
        for i, k in enumerate(KELAS):
            is_pred = (k == kelas)
            ax_card.text(
                -0.3, i,
                f"{INFO_KELAS[k]['emoji']} {k}",
                va='center', ha='left',
                fontsize=8.5,
                fontweight='bold' if is_pred else 'normal',
                color='#1A1A1A' if is_pred else '#888888'
            )

        # Nilai persentase di ujung bar
        for bar, p in zip(bars, prob):
            if p > 0.02:
                ax_card.text(
                    bar.get_width() + 0.5,
                    bar.get_y() + bar.get_height() / 2,
                    f'{p*100:.1f}%',
                    va='center', ha='left',
                    fontsize=7.5, color='#333333'
                )

        ax_card.set_xlim(-0.5, 108)
        ax_card.set_ylim(-0.6, len(KELAS) + 1.9)
        ax_card.set_yticks([])
        ax_card.set_xticks([])
        ax_card.spines['top'].set_visible(False)
        ax_card.spines['right'].set_visible(False)
        ax_card.spines['left'].set_visible(False)
        ax_card.spines['bottom'].set_color('#E0E0E0')

    # ══════════════════════════════════════════════════════════════════════════
    # PANEL BAWAH — Tabel ringkasan semua model
    # ══════════════════════════════════════════════════════════════════════════
    ax_tbl = fig.add_subplot(gs[2, 1:])
    ax_tbl.axis('off')

    # Header
    ax_tbl.text(
        0.5, 1.02, 'Ringkasan Prediksi Semua Model',
        ha='center', va='bottom',
        fontsize=11, fontweight='bold', color='#1A1A2E',
        transform=ax_tbl.transAxes
    )

    # Data tabel
    col_labels  = ['Model', 'Prediksi', 'Jenis Sampah', 'Confidence']
    table_data  = []
    cell_colors = []

    for nm in model_urutan:
        if nm not in hasil:
            continue
        d   = hasil[nm]
        k   = d['kelas']
        inf = INFO_KELAS[k]
        table_data.append([
            nm,
            f"{inf['emoji']} {k}",
            inf['label'],
            f"{d['confidence']*100:.1f}%"
        ])
        warna_hex = inf['warna'] + '33'  # transparan
        cell_colors.append(['#F5F5F5', warna_hex, '#F5F5F5', warna_hex])

    tbl = ax_tbl.table(
        cellText=table_data,
        colLabels=col_labels,
        cellLoc='center',
        loc='center',
        cellColours=cell_colors,
        colColours=['#1A1A2E'] * 4
    )
    tbl.auto_set_font_size(False)
    tbl.set_fontsize(10)
    tbl.scale(1, 1.6)

    # Warna teks header tabel
    for j in range(len(col_labels)):
        tbl[(0, j)].set_text_props(color='white', fontweight='bold')

    plt.savefig('hasil_klasifikasi.png', dpi=180, bbox_inches='tight',
                facecolor='#F8F9FA')
    plt.show()
    print('\n✅ Hasil disimpan: hasil_klasifikasi.png')


print('✅ Fungsi prediksi siap!')

# ─── UPLOAD GAMBAR ──────────────────────────────────────────────────────────
print(' Silakan pilih gambar sampah dari komputer Anda...')
uploaded = files.upload()

if not uploaded:
    print(' Tidak ada file yang diupload.')
else:
    nama_file = list(uploaded.keys())[0]
    print(f'\n File diterima: {nama_file}')
    print(' Memproses gambar...')

    img_asli, hasil = prediksi_semua(nama_file)

    # Cetak ringkasan teks di konsol
    print('\n' + '='*45)
    print('  HASIL KLASIFIKASI SAMPAH')
    print('='*45)
    for model_name, data in hasil.items():
        inf = INFO_KELAS[data['kelas']]
        print(f"  {model_name:<15}: {inf['emoji']} {inf['label']:<20} ({data['confidence']*100:.1f}%)")
    print('='*45)

    # Tampilkan visualisasi lengkap
    tampilkan_hasil(img_asli, hasil, nama_file)

